language: python
python:
- "3.5"
install:
# For local unit and integration tests
- pip install -r requirements.txt
# To test the Docker container itself
- docker-compose build
script:
- bash -c "echo 'Run tests here'"
