version: '3'
services:
  politik-bei-uns-daemon:
    container_name: politik-bei-uns-daemon
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: ['sleep', '60000']
    #entrypoint: ["python3", "manage.py", "daemon", "start-foreground"]
    networks:
      shared_politik-bei-uns:
        aliases:
          - daemon

networks:
  shared_politik-bei-uns:
    external: true
